import LegalLayout, { Section, Ul } from './LegalLayout'

function Terms() {
  return (
    <LegalLayout title="Terms & Conditions" updated="September 2026">
      <p className="text-[15px] leading-relaxed text-stone-600 dark:text-stone-400">
        These terms govern your use of Campus Coin (the "Service"), a student budgeting and
        expense-tracking application. By creating an account or otherwise using the Service, you
        agree to these terms. If you don't agree with them, please don't use Campus Coin.
      </p>

      <Section title="1. What Campus Coin is — and isn't">
        <p>
          Campus Coin helps you manually log income and expenses, organize them into categories,
          set monthly budgets, and view reports and saving tips based on your own transaction
          history.
        </p>
        <p>
          Campus Coin does <strong>not</strong> connect to any bank, card, or payment network. It
          does not move money, process payments, or verify real account balances. Every
          transaction you see in the app was typed in (or imported from a CSV) by you or another
          user of your account — none of it is pulled from a real financial institution.
        </p>
      </Section>

      <Section title="2. Your account">
        <Ul>
          <li>You must provide a real name and a working email address to register.</li>
          <li>You're responsible for keeping your password secure and for all activity under your account.</li>
          <li>
            Administrator accounts are separate from student accounts and are only issued to the
            project's admin team.
          </li>
          <li>
            If we (or you) believe your account has been compromised, reset your password
            immediately from the login page — this also signs out every other active session on
            the account.
          </li>
        </Ul>
      </Section>

      <Section title="3. Acceptable use">
        <p>You agree not to:</p>
        <Ul>
          <li>Use the Service for anything unlawful, or to misrepresent your identity.</li>
          <li>Attempt to access another user's account or data without authorization.</li>
          <li>
            Probe, scan, or attack the Service's infrastructure, or attempt to bypass its rate
            limits, authentication, or other security controls.
          </li>
          <li>Upload malicious files or attempt to inject harmful content through any input field.</li>
        </Ul>
        <p>
          We may disable an account that violates these terms, consistent with our{' '}
          <a href="/privacy">Privacy Policy</a>.
        </p>
      </Section>

      <Section title="4. Saving tips, insights & anything labelled AI">
        <p>
          Features like the saving-tips feed, "This month's insight," and duplicate/large-transaction
          flags are generated by deterministic, rule-based logic that compares your own transaction
          history against your own past averages and budgets — not a live AI model, and not
          personalized financial advice from a licensed advisor.
        </p>
        <p>
          Treat every tip, insight, or flag as a starting point for your own judgment, not as
          professional financial, tax, or investment advice. Campus Coin is a habit-tracking tool,
          not a financial advisor.
        </p>
      </Section>

      <Section title="5. Service availability">
        <p>
          Campus Coin runs on free-tier hosting and a free-tier database. We aim to keep it
          available, but we don't guarantee uninterrupted uptime, and scheduled or unscheduled
          downtime can happen without notice. Back up anything important to you by exporting your
          reports.
        </p>
      </Section>

      <Section title="6. Intellectual property">
        <p>
          The Campus Coin name, logo, and interface design belong to the SharpStackers team. The
          underlying source code was built as an academic project for TechWiz 7 (Aptech Limited).
          You retain ownership of the transaction data and content you enter into your own account.
        </p>
      </Section>

      <Section title="7. Termination">
        <p>
          You may stop using the Service at any time. We may suspend or disable an account that
          violates these terms, is inactive for an extended period, or as otherwise needed to keep
          the Service secure and functional.
        </p>
      </Section>

      <Section title="8. Disclaimer & limitation of liability">
        <p>
          Campus Coin is provided "as is," without warranties of any kind, express or implied. To
          the fullest extent permitted by law, the SharpStackers team is not liable for any
          indirect, incidental, or consequential damages arising from your use of, or inability to
          use, the Service — including decisions made based on its saving tips or insights.
        </p>
      </Section>

      <Section title="9. Changes to these terms">
        <p>
          We may update these terms as the Service evolves. Material changes will be reflected by
          updating the date at the top of this page. Continuing to use Campus Coin after a change
          means you accept the updated terms.
        </p>
      </Section>

      <Section title="10. Contact">
        <p>
          Questions about these terms? Reach the SharpStackers team through the project repository
          at{' '}
          <a href="https://github.com/aaliyandevs/CampusCoin" target="_blank" rel="noreferrer">
            github.com/aaliyandevs/CampusCoin
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  )
}

export default Terms
